//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Detalle { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
