CREATE TABLE Ciudades(
	Id int IDENTITY(1,1) NOT NULL,
	Nombre varchar(50) NOT NULL,
 CONSTRAINT PK_Ciudades PRIMARY KEY CLUSTERED (Id ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]) ON [PRIMARY]
GO


